numprocs=128

*******
  Note: NeuroML import failed; import/export functions for NeuroML will not be available. 
  Install the pyNeuroML & libNeuroML Python packages: https://www.neuroml.org/getneuroml
*******


Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
	0 
Loading simConfig...
	0 
	0 
	0 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...
Loading simConfig...
	0 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...
	0 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...
	0 
Loading simConfig...
	0 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Loading simConfig...
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Loading simConfig...
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...
	0 
	0 
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
	0 
	0 
	0 
	0 
	0 
	0 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
	0 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
	0 
	0 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
	0 
Loading simConfig...
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
	0 
	0 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
	0 
Loading simConfig...
	0 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
	0 
Loading simConfig...
Loading simConfig...
	0 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
	0 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
	0 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Loading simConfig...
Loading simConfig...
Loading simConfig...
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Loading simConfig...
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...
	0 
Loading simConfig...
	0 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...
	0 
	0 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Loading simConfig...
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
	0 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...
	0 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...
	0 
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...
Loading simConfig...
	0 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...
	0 
	0 
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
	0 
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
	0 
	0 
	0 
	0 
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
	0 
	0 
	0 
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
	0 
	0 
	0 
	0 
	0 
	0 
	0 
	0 
	0 
	0 
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
	0 
	0 
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
	0 
	0 
	0 
	0 
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
	0 
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
	0 
	0 
	0 
	0 
	0 
	0 
	0 
	0 
	0 
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
	0 
	0 
	0 
	0 
	0 
	0 
	0 
	0 
	0 
	0 
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
	0 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Loading simConfig...
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
	0 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
	0 
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
	0 
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
	0 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...
	0 
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Loading simConfig...
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Loading simConfig...
Loading simConfig...
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Loading simConfig...
Loading simConfig...
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Loading simConfig...
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...
Loading simConfig...
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...
	0 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...
	0 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...
	0 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
	0 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v53_batch24/gen_76/gen_76_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Loading simConfig...
	0 
	0 
	0 
	0 
	0 
	0 
	0 
	0 
	0 
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
	0 
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
	0 
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
	0 
	0 
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
	0 
	0 
	0 
	0 
	0 
	0 
	0 
	0 
	0 
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
	0 
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
	0 
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
	0 
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
	0 
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
	0 
	0 
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
	0 
	0 
	0 
	0 
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
	0 
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
	0 
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
	0 
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
	0 
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py
Importing netParams from ../data/v53_batch24/v53_batch24_netParams.py

Creating network of 22 cell populations on 128 hosts...
  Number of cells on node 125: 74 
  Number of cells on node 123: 74 
  Number of cells on node 3: 75 
  Number of cells on node 2: 75 
  Number of cells on node 4: 75 
  Number of cells on node 1: 75 
  Number of cells on node 7: 75 
  Number of cells on node 6: 75 
  Number of cells on node 5: 75 
  Number of cells on node 0: 75 
  Done; cell creation time = 0.84 s.
Making connections...
  Number of cells on node 105: 74 
  Number of cells on node 17: 75 
  Number of cells on node 102: 74 
  Number of cells on node 119: 74 
  Number of cells on node 76: 74 
  Number of cells on node 120: 74 
  Number of cells on node 54: 74 
  Number of cells on node 91: 74 
  Number of cells on node 86: 74 
  Number of cells on node 71: 74 
  Number of cells on node 124: 74 
  Number of cells on node 58: 74 
  Number of cells on node 48: 74 
  Number of cells on node 89: 74 
  Number of cells on node 47: 74 
  Number of cells on node 83: 74 
  Number of cells on node 30: 75 
  Number of cells on node 11: 75 
  Number of cells on node 66: 74 
  Number of cells on node 108: 74 
  Number of cells on node 37: 75 
  Number of cells on node 21: 75 
  Number of cells on node 103: 74 
  Number of cells on node 113: 74 
  Number of cells on node 77: 74 
  Number of cells on node 101: 74 
  Number of cells on node 114: 74 
  Number of cells on node 74: 74 
  Number of cells on node 126: 74 
  Number of cells on node 62: 74 
  Number of cells on node 53: 74 
  Number of cells on node 94: 74 
  Number of cells on node 45: 74 
  Number of cells on node 80: 74 
  Number of cells on node 26: 75 
  Number of cells on node 12: 75 
  Number of cells on node 67: 74 
  Number of cells on node 104: 74 
  Number of cells on node 34: 75 
  Number of cells on node 23: 75 
  Number of cells on node 121: 74 
  Number of cells on node 61: 74 
  Number of cells on node 50: 74 
  Number of cells on node 92: 74 
  Number of cells on node 44: 74 
  Number of cells on node 85: 74 
  Number of cells on node 31: 75 
  Number of cells on node 15: 75 
  Number of cells on node 70: 74 
  Number of cells on node 107: 74 
  Number of cells on node 35: 75 
  Number of cells on node 22: 75 
  Number of cells on node 99: 74 
  Number of cells on node 118: 74 
  Number of cells on node 75: 74 
  Number of cells on node 122: 74 
  Number of cells on node 56: 74 
  Number of cells on node 52: 74 
  Number of cells on node 95: 74 
  Number of cells on node 40: 74 
  Number of cells on node 81: 74 
  Number of cells on node 29: 75 
  Number of cells on node 13: 75 
  Number of cells on node 65: 74 
  Number of cells on node 110: 74 
  Number of cells on node 33: 75 
  Number of cells on node 19: 75 
  Number of cells on node 96: 74 
  Number of cells on node 116: 74 
  Number of cells on node 72: 74 
  Number of cells on node 43: 74 
  Number of cells on node 87: 74 
  Number of cells on node 25: 75 
  Number of cells on node 14: 75 
  Number of cells on node 69: 74 
  Number of cells on node 111: 74 
  Number of cells on node 32: 75 
  Number of cells on node 18: 75 
  Number of cells on node 98: 74 
  Number of cells on node 112: 74 
  Number of cells on node 78: 74 
  Number of cells on node 127: 74 
  Number of cells on node 57: 74 
  Number of cells on node 51: 74 
  Number of cells on node 93: 74 
  Number of cells on node 59: 74 
  Number of cells on node 55: 74 
  Number of cells on node 88: 74 
  Number of cells on node 46: 74 
  Number of cells on node 82: 74 
  Number of cells on node 24: 75 
  Number of cells on node 9: 75 
  Number of cells on node 68: 74 
  Number of cells on node 109: 74 
  Number of cells on node 38: 75 
  Number of cells on node 16: 75 
  Number of cells on node 100: 74 
  Number of cells on node 117: 74 
  Number of cells on node 73: 74 
  Number of cells on node 60: 74 
  Number of cells on node 49: 74 
  Number of cells on node 90: 74 
  Number of cells on node 41: 74 
  Number of cells on node 84: 74 
  Number of cells on node 27: 75 
  Number of cells on node 8: 75 
  Number of cells on node 64: 74 
  Number of cells on node 106: 74 
  Number of cells on node 39: 75 
  Number of cells on node 20: 75 
  Number of cells on node 97: 74 
  Number of cells on node 115: 74 
  Number of cells on node 79: 74 
  Number of cells on node 63: 74 
  Number of cells on node 42: 74 
  Number of cells on node 28: 75 
  Number of cells on node 10: 75 
  Number of cells on node 36: 75 
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Number of connections on node 122: 10411 
  Number of synaptic contacts on node 122: 37433 
  Number of connections on node 120: 10251 
  Number of synaptic contacts on node 120: 36298 
  Number of connections on node 121: 10287 
  Number of synaptic contacts on node 121: 37786 
  Number of connections on node 124: 10308 
  Number of synaptic contacts on node 124: 37262 
  Number of connections on node 123: 10151 
  Number of synaptic contacts on node 123: 36528 
  Number of connections on node 125: 10160 
  Number of synaptic contacts on node 125: 36191 
  Number of connections on node 126: 9946 
  Number of synaptic contacts on node 126: 35877 
  Number of connections on node 127: 10624 
  Number of synaptic contacts on node 127: 43989 
  Number of connections on node 68: 10364 
  Number of synaptic contacts on node 68: 42285 
  Number of connections on node 119: 9811 
  Number of synaptic contacts on node 119: 35257 
  Number of connections on node 67: 10852 
  Number of synaptic contacts on node 67: 45383 
  Number of connections on node 118: 10064 
  Number of connections on node 65: 10339 
  Number of synaptic contacts on node 65: 42316 
  Number of synaptic contacts on node 118: 36991 
  Number of connections on node 48: 10640 
  Number of synaptic contacts on node 48: 42367 
  Number of connections on node 70: 10622 
  Number of synaptic contacts on node 70: 43521 
  Number of connections on node 64: 10446 
  Number of synaptic contacts on node 64: 43234 
  Number of connections on node 71: 10393 
  Number of synaptic contacts on node 71: 42227 
  Number of connections on node 69: 10826 
  Number of synaptic contacts on node 69: 45398 
  Number of connections on node 66: 10753 
  Number of synaptic contacts on node 66: 44364 
  Number of connections on node 111: 10143 
  Number of synaptic contacts on node 111: 36071 
  Number of connections on node 49: 10581 
  Number of synaptic contacts on node 49: 44873 
  Number of connections on node 51: 10391 
  Number of synaptic contacts on node 51: 41830 
  Number of connections on node 53: 10722 
  Number of synaptic contacts on node 53: 44810 
  Number of connections on node 19: 10604 
  Number of synaptic contacts on node 19: 42849 
  Number of connections on node 115: 10023 
  Number of synaptic contacts on node 115: 35582 
  Number of connections on node 55: 10563 
  Number of synaptic contacts on node 55: 42076 
  Number of connections on node 117: 10199 
  Number of synaptic contacts on node 117: 36422 
  Number of connections on node 112: 10098 
  Number of synaptic contacts on node 112: 36196 
  Number of connections on node 54: 10227 
  Number of synaptic contacts on node 54: 41730 
  Number of connections on node 58: 10294 
  Number of synaptic contacts on node 58: 42693 
  Number of connections on node 114: 10624 
  Number of synaptic contacts on node 114: 38869 
  Number of connections on node 44: 10393 
  Number of synaptic contacts on node 44: 42926 
  Number of connections on node 116: 10174 
  Number of synaptic contacts on node 116: 36759 
  Number of connections on node 52: 10599 
  Number of synaptic contacts on node 52: 44879 
  Number of connections on node 50: 11145 
  Number of synaptic contacts on node 50: 47497 
  Number of connections on node 57: 10488 
  Number of synaptic contacts on node 57: 42282 
  Number of connections on node 56: 10680 
  Number of synaptic contacts on node 56: 43636 
  Number of connections on node 39: 10383 
  Number of synaptic contacts on node 39: 41875 
  Number of connections on node 20: 10874 
  Number of synaptic contacts on node 20: 43400 
  Number of connections on node 34: 10446 
  Number of synaptic contacts on node 34: 42335 
  Number of connections on node 16: 11056 
  Number of synaptic contacts on node 16: 44256 
  Number of connections on node 113: 10745 
  Number of synaptic contacts on node 113: 40080 
  Number of connections on node 60: 10914 
  Number of synaptic contacts on node 60: 45671 
  Number of connections on node 15: 10863 
  Number of synaptic contacts on node 15: 43369 
  Number of connections on node 37: 10589 
  Number of synaptic contacts on node 37: 43459 
  Number of connections on node 36: 10798 
  Number of synaptic contacts on node 36: 44293 
  Number of connections on node 23: 10789 
  Number of synaptic contacts on node 23: 43396 
  Number of connections on node 75: 10292 
  Number of synaptic contacts on node 75: 42536 
  Number of connections on node 59: 10606 
  Number of synaptic contacts on node 59: 43917 
  Number of connections on node 40: 10491 
  Number of synaptic contacts on node 40: 42952 
  Number of connections on node 25: 11047 
  Number of synaptic contacts on node 25: 45411 
  Number of connections on node 17: 11148 
  Number of synaptic contacts on node 17: 45484 
  Number of connections on node 74: 10522 
  Number of synaptic contacts on node 74: 42378 
  Number of connections on node 62: 10441 
  Number of synaptic contacts on node 62: 43291 
  Number of connections on node 5: 10777 
  Number of synaptic contacts on node 5: 42901 
  Number of connections on node 4: 11208 
  Number of synaptic contacts on node 4: 45087 
  Number of connections on node 61: 10961 
  Number of synaptic contacts on node 61: 45936 
  Number of connections on node 41: 10477 
  Number of synaptic contacts on node 41: 42742 
  Number of connections on node 28: 10811 
  Number of synaptic contacts on node 28: 43503 
  Number of connections on node 11: 10709 
  Number of synaptic contacts on node 11: 43166 
  Number of connections on node 33: 11112 
  Number of synaptic contacts on node 33: 46658 
  Number of connections on node 21: 11250 
  Number of synaptic contacts on node 21: 46807 
  Number of connections on node 73: 10682 
  Number of synaptic contacts on node 73: 44379 
  Number of connections on node 6: 11077 
  Number of synaptic contacts on node 6: 43277 
  Number of connections on node 3: 11008 
  Number of synaptic contacts on node 3: 44144 
  Number of connections on node 1: 11008 
  Number of synaptic contacts on node 1: 43902 
  Number of connections on node 7: 10709 
  Number of synaptic contacts on node 7: 43682 
  Number of connections on node 63: 10822 
  Number of synaptic contacts on node 63: 44855 
  Number of connections on node 47: 10620 
  Number of connections on node 31: 10654 
  Number of synaptic contacts on node 31: 42902 
  Number of connections on node 9: 10877 
  Number of synaptic contacts on node 9: 44144 
  Number of connections on node 105: 10207 
  Number of synaptic contacts on node 105: 42992 
  Number of connections on node 22: 10721 
  Number of synaptic contacts on node 22: 42555 
  Number of connections on node 76: 10618 
  Number of synaptic contacts on node 76: 42838 
  Number of connections on node 2: 10886 
  Number of synaptic contacts on node 2: 44152 
  Number of connections on node 0: 10980 
  Number of synaptic contacts on node 0: 44286 
  Number of synaptic contacts on node 47: 43039 
  Number of connections on node 27: 10866 
  Number of synaptic contacts on node 27: 43873 
  Number of connections on node 13: 11105 
  Number of synaptic contacts on node 13: 45740 
  Number of connections on node 108: 10149 
  Number of connections on node 32: 10886 
  Number of synaptic contacts on node 32: 43534 
  Number of connections on node 18: 10908 
  Number of synaptic contacts on node 18: 43562 
  Number of connections on node 77: 10637 
  Number of synaptic contacts on node 77: 44812 
  Number of connections on node 45: 11072 
  Number of synaptic contacts on node 45: 47103 
  Number of connections on node 24: 10976 
  Number of synaptic contacts on node 24: 44403 
  Number of connections on node 14: 10831 
  Number of synaptic contacts on node 14: 44169 
  Number of synaptic contacts on node 108: 42256 
  Number of connections on node 35: 10670 
  Number of synaptic contacts on node 35: 44318 
  Number of connections on node 72: 10461 
  Number of synaptic contacts on node 72: 42868 
  Number of connections on node 46: 10818 
  Number of synaptic contacts on node 46: 45098 
  Number of connections on node 30: 10908 
  Number of synaptic contacts on node 30: 43327 
  Number of connections on node 8: 10767 
  Number of synaptic contacts on node 8: 44161 
  Number of connections on node 106: 10352 
  Number of synaptic contacts on node 106: 42653 
  Number of connections on node 38: 10864 
  Number of synaptic contacts on node 38: 45520 
  Number of connections on node 42: 10947 
  Number of synaptic contacts on node 42: 45998 
  Number of connections on node 29: 11253 
  Number of synaptic contacts on node 29: 46194 
  Number of connections on node 10: 11533 
  Number of synaptic contacts on node 10: 46893 
  Number of connections on node 109: 10250 
  Number of synaptic contacts on node 109: 42751 
  Number of connections on node 43: 10782 
  Number of synaptic contacts on node 43: 44848 
  Number of connections on node 26: 11221 
  Number of synaptic contacts on node 26: 45752 
  Number of connections on node 12: 11036 
  Number of synaptic contacts on node 12: 45415 
  Number of connections on node 110: 10514 
  Number of synaptic contacts on node 110: 43225 
  Number of connections on node 107: 10188 
  Number of synaptic contacts on node 107: 42775 
  Number of connections on node 104: 10671 
  Number of synaptic contacts on node 104: 43100 
  Number of connections on node 87: 10243 
  Number of synaptic contacts on node 87: 48089 
  Number of connections on node 85: 10086 
  Number of synaptic contacts on node 85: 47228 
  Number of connections on node 91: 10435 
  Number of synaptic contacts on node 91: 47724 
  Number of connections on node 86: 10291 
  Number of synaptic contacts on node 86: 46464 
  Number of connections on node 90: 10134 
  Number of synaptic contacts on node 90: 47995 
  Number of connections on node 93: 10564 
  Number of synaptic contacts on node 93: 49675 
  Number of connections on node 80: 10251 
  Number of synaptic contacts on node 80: 48689 
  Number of connections on node 82: 10644 
  Number of synaptic contacts on node 82: 50525 
  Number of connections on node 89: 10416 
  Number of synaptic contacts on node 89: 48114 
  Number of connections on node 94: 10468 
  Number of synaptic contacts on node 94: 47790 
  Number of connections on node 84: 10467 
  Number of synaptic contacts on node 84: 49541 
  Number of connections on node 95: 10381 
  Number of synaptic contacts on node 95: 49594 
  Number of connections on node 102: 10220 
  Number of synaptic contacts on node 102: 40796 
  Number of connections on node 81: 10665 
  Number of synaptic contacts on node 81: 49115 
  Number of connections on node 79: 10636 
  Number of synaptic contacts on node 79: 47979 
  Number of connections on node 78: 10895 
  Number of synaptic contacts on node 78: 50310 
  Number of connections on node 88: 10512 
  Number of synaptic contacts on node 88: 48915 
  Number of connections on node 83: 10528 
  Number of synaptic contacts on node 83: 48585 
  Number of connections on node 96: 10273 
  Number of synaptic contacts on node 96: 47892 
  Number of connections on node 92: 10293 
  Number of synaptic contacts on node 92: 49020 
  Number of connections on node 101: 10572 
  Number of synaptic contacts on node 101: 43979 
  Number of connections on node 100: 10188 
  Number of synaptic contacts on node 100: 47165 
  Number of connections on node 103: 10240 
  Number of synaptic contacts on node 103: 42594 
  Number of connections on node 97: 10395 
  Number of synaptic contacts on node 97: 48388 
  Number of connections on node 98: 10268 
  Number of synaptic contacts on node 98: 48933 
  Done; cell connection time = 76.58 s.
  Number of connections on node 99: 10563 
  Number of synaptic contacts on node 99: 49813 
  Number of stims on node 7: 0 
  Number of stims on node 6: 0 
  Number of stims on node 3: 0 
  Number of stims on node 5: 0 
  Number of stims on node 2: 0 
  Number of stims on node 1: 0 
  Number of stims on node 0: 0 
  Number of stims on node 4: 0 
  Number of stims on node 63: 0 
  Number of stims on node 95: 0 
  Number of stims on node 33: 0 
  Number of stims on node 79: 0 
  Number of stims on node 62: 0 
  Number of stims on node 93: 0 
  Number of stims on node 39: 0 
  Number of stims on node 78: 0 
  Done; cell stims creation time = 0.00 s.
  Number of stims on node 114: 0 
  Number of stims on node 74: 0 
  Number of stims on node 127: 0 
  Number of stims on node 58: 0 
  Number of stims on node 50: 0 
  Number of stims on node 91: 0 
  Number of stims on node 43: 0 
  Number of stims on node 80: 0 
  Number of stims on node 26: 0 
  Number of stims on node 11: 0 
  Number of stims on node 67: 0 
  Number of stims on node 104: 0 
  Number of stims on node 38: 0 
  Number of stims on node 18: 0 
  Number of stims on node 99: 0 
  Number of stims on node 124: 0 
  Number of stims on node 57: 0 
  Number of stims on node 55: 0 
  Number of stims on node 90: 0 
  Number of stims on node 41: 0 
  Number of stims on node 84: 0 
  Number of stims on node 29: 0 
  Number of stims on node 12: 0 
  Number of stims on node 68: 0 
  Number of stims on node 111: 0 
  Number of stims on node 36: 0 
  Number of stims on node 20: 0 
  Number of stims on node 100: 0 
  Number of stims on node 119: 0 
  Number of stims on node 76: 0 
  Number of stims on node 28: 0 
  Number of stims on node 10: 0 
  Number of stims on node 66: 0 
  Number of stims on node 109: 0 
  Number of stims on node 37: 0 
  Number of stims on node 16: 0 
  Number of stims on node 101: 0 
  Number of stims on node 112: 0 
  Number of stims on node 73: 0 
  Number of stims on node 120: 0 
  Number of stims on node 59: 0 
  Number of stims on node 49: 0 
  Number of stims on node 89: 0 
  Number of stims on node 47: 0 
  Number of stims on node 83: 0 
  Number of stims on node 126: 0 
  Number of stims on node 61: 0 
  Number of stims on node 52: 0 
  Number of stims on node 94: 0 
  Number of stims on node 42: 0 
  Number of stims on node 86: 0 
  Number of stims on node 31: 0 
  Number of stims on node 14: 0 
  Number of stims on node 70: 0 
  Number of stims on node 105: 0 
  Number of stims on node 35: 0 
  Number of stims on node 23: 0 
  Number of stims on node 97: 0 
  Number of stims on node 113: 0 
  Number of stims on node 72: 0 
  Number of stims on node 122: 0 
  Number of stims on node 60: 0 
  Number of stims on node 53: 0 
  Number of stims on node 92: 0 
  Number of stims on node 44: 0 
  Number of stims on node 81: 0 
  Number of stims on node 27: 0 
  Number of stims on node 13: 0 
  Number of stims on node 71: 0 
  Number of stims on node 107: 0 
  Number of stims on node 32: 0 
  Number of stims on node 17: 0 
  Number of stims on node 98: 0 
  Number of stims on node 118: 0 
  Number of stims on node 75: 0 
  Number of stims on node 9: 0 
  Number of stims on node 69: 0 
  Number of stims on node 108: 0 
  Number of stims on node 34: 0 
  Number of stims on node 19: 0 
  Number of stims on node 102: 0 
  Number of stims on node 115: 0 
  Number of stims on node 77: 0 
  Number of stims on node 125: 0 
  Number of stims on node 56: 0 
  Number of stims on node 54: 0 
  Number of stims on node 88: 0 
  Number of stims on node 46: 0 
  Number of stims on node 85: 0 
  Number of stims on node 25: 0 

Running simulation for 1500.0 ms...
  Number of stims on node 121: 0 
  Number of stims on node 51: 0 
  Number of stims on node 40: 0 
  Number of stims on node 82: 0 
  Number of stims on node 24: 0 
  Number of stims on node 15: 0 
  Number of stims on node 64: 0 
  Number of stims on node 106: 0 
  Number of stims on node 21: 0 
  Number of stims on node 103: 0 
  Number of stims on node 117: 0 
  Number of stims on node 123: 0 
  Number of stims on node 48: 0 
  Number of stims on node 45: 0 
  Number of stims on node 87: 0 
  Number of stims on node 30: 0 
  Number of stims on node 8: 0 
  Number of stims on node 65: 0 
  Number of stims on node 110: 0 
  Number of stims on node 22: 0 
  Number of stims on node 96: 0 
  Number of stims on node 116: 0 
0.1 s
0.2 s
0.3 s
0.4 s
0.5 s
0.6 s
0.7 s
0.8 s
0.9 s
1 s
1.1 s
1.2 s
1.3 s
1.4 s
  Done; run time = 481.57 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 1.96 s.

Analyzing...
  Cells: 9512
  Connections: 0 (0.00 per cell)
  Spikes: 75874 (5.32 Hz)
   IT2 : 8.590 Hz
   SOM2 : 26.581 Hz
   PV2 : 7.146 Hz
   IT4 : 7.867 Hz
   IT5A : 26.774 Hz
   SOM5A : 22.381 Hz
   PV5A : 21.952 Hz
   IT5B : 5.482 Hz
   PT5B : 36.350 Hz
   SOM5B : 8.043 Hz
   PV5B : 24.310 Hz
   IT6 : 16.477 Hz
   CT6 : 4.022 Hz
   SOM6 : 18.970 Hz
   PV6 : 0.420 Hz
   TPO : 2.397 Hz
   TVL : 1.845 Hz
   S1 : 2.590 Hz
   S2 : 1.571 Hz
   cM1 : 1.207 Hz
   M2 : 1.859 Hz
   OC : 2.047 Hz
  Simulated time: 1.5 s; 128 workers
  Run time: 481.57 s
Saving output as ../data/v53_batch24/gen_76/gen_76_cand_16.json  ... 
Finished saving!
  Done; saving time = 1.05 s.
Plotting raster...
  Done; plotting time = 10.11 s

Total time = 575.90 s
